validation for duplicate dag ids
viaduct-ai/pre-commit-hooks pull request #4
Opened 2021-03-04 21:00 UTC by jay-bhambhani

it was pretty complicated to write tests for this given the need for a dagbag and all the airflow stuff. tested manually by adding lines to dags/tests and ensuring that it worked as expected.

2021-03-04 22:39 UTC, jpugliesi reviewed
An alternative to stripping the characters from the string is to use `eval`. this example parses the dag_ids instead of the counter
```
        # absolute hack to extract each individual file's dag ids
        dags = [dag for stat in dagbag.dagbag_stats for dag in eval(stat.dags)]
        duplicate_dags = set([dag for dag in dags if dags.count(dag) > 1])

        if duplicate_dags:
            print(f'Duplicate dag_ids found: {duplicate_dags}')
            assert False

```

2021-03-04 22:49 UTC, jpugliesi requested changes
This actually is not very portable because it assumes the runtime environment has python with airflow correctly installed, with dependencies. A better approach imo would be:
1. Add a marked test for this validation (under `test_import_dags.py`:
```
    @pytest.mark.precommit
    @pytest.mark.slow
    def test_duplicate_dags(self, dagbag):
        """Test for duplicate DAGs."""
        # absolute hack to extract each individual file's dag ids
        dags = [dag for stat in dagbag.dagbag_stats for dag in eval(stat.dags)]
        duplicate_dags = set([dag for dag in dags if dags.count(dag) > 1])

        if duplicate_dags:
            print(f'Duplicate dag_ids found: {duplicate_dags}')
            assert False
```
2. Create a make recipe to run this test only:
```
.PHONY: pre-commit
pre-commit:
	# Runs pre-commit tests
	docker build -t viaduct.ai/airflow-test -f tests/Dockerfile ${PWD}
	docker run viaduct.ai/airflow-test '-m precommit'
```

3. Run `make pre-commit` in the pre-commit hook

2021-03-04 22:49 UTC, jpugliesi commented on .pre-commit-hooks.yaml
> +  description: 'Ensure that we do not have duplicate dag ids names'
```suggestion
  description: 'Ensure that we do not have duplicate dag ids'
```

2021-03-04 22:49 UTC, jpugliesi commented on .pre-commit-hooks.yaml
> +  name: 'Ensure that we do not have duplicate dag ids names'
```suggestion
  name: 'Ensure that we do not have duplicate dag ids'
```

2021-03-05 01:25 UTC, jay-bhambhani commented
> An alternative to stripping the characters from the string is to use `eval`. this example parses the dag_ids instead of the counter
> 
> ```
>         # absolute hack to extract each individual file's dag ids
>         dags = [dag for stat in dagbag.dagbag_stats for dag in eval(stat.dags)]
>         duplicate_dags = set([dag for dag in dags if dags.count(dag) > 1])
> 
>         if duplicate_dags:
>             print(f'Duplicate dag_ids found: {duplicate_dags}')
>             assert False
> ```

the only reason i didn't use eval is that I have always been told it is unsafe - so I try my best to avoid usage where I can.

2021-03-05 15:53 UTC, devstein commented
Why do we need this as `pre-commit` hook? Why not only make it part of CI?

2021-03-05 16:04 UTC, jay-bhambhani commented
it was asked for as a precommit hook https://viaduct-ai.slack.com/archives/CQ397F9GA/p1614806104054300. we could make it a test, but i think it is quite nice to have as a pre-commit hook

2021-03-05 18:17 UTC, jay-bhambhani commented
closing to make ci

2021-03-05 18:17 UTC, closed without merging